version: '3'

volumes:
  postgres-data:
  rabbit-data:
  uploads-data:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: PG_PASS
      POSTGRES_DB: app
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 18888:8080

  frontend:
    build:
      context: massistant-web-app
    restart: always
    ports:
      - 8000:8080
    command: [ "npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "8080" ]

  api:
    build:
      context: massistant-api
    restart: always
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: "postgresql://postgres:PG_PASS@db:5432/app"
    volumes:
      - uploads-data:/app/uploads
    command: [ "sh", "entrypoint.sh" ]

