version: '3'

volumes:
  postgres-data:
  rabbit-data:
  uploads-data:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

  rabbit:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    ports:
      - 15762:15672
      # - 5672:5672

  frontend:
    build:
      context: massistant-web-app
    restart: always
    ports:
      - 8000:8080
    command: [ "npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "8080" ]

  api:
    build:
      context: massistant-api
    restart: always
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: "postgresql://postgres:postgres@db:5432/app"
    volumes:
      - uploads-data:/app/uploads
    command: [ "sh", "entrypoint.sh" ]

