"""summary and glossary fields

Revision ID: 32c130872762
Revises: 0ce354459152
Create Date: 2023-11-25 00:15:41.687149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32c130872762'
down_revision: Union[str, None] = '0ce354459152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('konspekt_uploads', sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('konspekt_uploads', sa.Column('glossary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('konspekt_uploads', 'glossary')
    op.drop_column('konspekt_uploads', 'summary')
    # ### end Alembic commands ###
