"""init

Revision ID: a35ecaffa8d6
Revises: 
Create Date: 2023-11-23 23:37:49.807616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35ecaffa8d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('konspekt_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_konspekt_uploads_created_at'), 'konspekt_uploads', ['created_at'], unique=False)
    op.create_index(op.f('ix_konspekt_uploads_filename'), 'konspekt_uploads', ['filename'], unique=True)
    op.create_index(op.f('ix_konspekt_uploads_id'), 'konspekt_uploads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_konspekt_uploads_id'), table_name='konspekt_uploads')
    op.drop_index(op.f('ix_konspekt_uploads_filename'), table_name='konspekt_uploads')
    op.drop_index(op.f('ix_konspekt_uploads_created_at'), table_name='konspekt_uploads')
    op.drop_table('konspekt_uploads')
    # ### end Alembic commands ###
