name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker compose
      run: docker compose --file deploy-docker-compose.yml build

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Replace passwords
      run: sed -i -e "s/PG_PASS/${{ secrets.DATABASE_PASSWORD }}/" deploy-docker-compose.yml
    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "./"
        EXCLUDE: "dataset/"
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        TARGET: ${{ secrets.DEPLOY_TARGET }}
        SCRIPT_AFTER: cd ${{ secrets.DEPLOY_TARGET }} && docker compose --project-name massistant-demo --file deploy-docker-compose.yml up --build -d

