name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker compose
      run: docker compose --file deploy-docker-compose.yml build

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Qwe
      run: ssh root@demo.dungeon-massters.pro ls -la
    - name: Replace passwords
      run: sed -i -e "s/PG_PASS/${{ secrets.DATABASE_PASSWORD }}/" deploy-docker-compose.yml
    - name: Deploy Docker compose
      env:
        DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
      run: docker compose --project-name massistant-demo --file deploy-docker-compose.yml up --build -d


